version: "3.5"
services:
    browsercompat:
        build: .
        image: dwarf/vault:browsercompat
        container_name: browsercompat
        working_dir: /app/browsercompat
        volumes: 
            - ./:/app/browsercompat
        command: /bin/sh -c "while sleep 1000; do :; done"